@startuml
protocol   Controller {
    --Attributes--
    + Model model
    + View view
    --Functions--
    + void loop()
}
class   View {
    --Functions--
    + void printOptions()
}
class   Model {
    --Attributes--
    - World world
    --Methods--
    + void directControllerInput()
}

class World {
    --Attributes--
    - map[string][Location] locations
    - Location currLocation
    --Methods--
    + Location getCurrLocation()
    + Location setCurrLocation(string currLocName, string newLocName)
    - void createLocations(string filename)
    + void initialize()
}

class Location {
    --Attributes--
    - string name 
    - []string neighbors
    --Methods--
    + string getName()
    + string getNeighbors(string loc)

}

Controller <-- Model : controls >
Controller <-- View : controls >
Model <-- World : contains
World <-- Location : contains


@enduml