@startuml
protocol   Controller
class   View {
    --Functions--
    void printOptions()
}
class   Model {
    --Attributes--
    World world
    --Functions--
}

class World {
    map[]string Locations
}

Controller <-- Model : controls >
Controller <-- View : controls >
Model <-- World


@enduml